export const PERFUME =
    [
        {
            id: 0,
            name: 'Dior Sauvage EDP',
            image: '/image/Men/Dior Sauvage EDP.png',
            sex: 'Men',
            category: 'Unisex',
            style: 'Nam tính, Quyến rũ, Mạnh mẽ',
            fragrant: 'Aromantic Fougere (Hương Thơm Thảo Mộc)',
            origin: 'Ý',
            concentration: 'Eau De Toilette (EDT)',
            label: 'New',
            price: 5650000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Dior',
            cart_quantity: 0,
            rating: 4.7,
            description: 'Vào năm 2018, Dior giới thiệu phiên bản mới của Dior Sauvage đã ra mắt vào năm 2015 với nồng độ Eau De Parfum. Các thành phần với hơi hướng phương Đông và vani. Tạo nên mùi hương ngọt ngào, bí ẩn và gợi cảm.'
        },
        {
            id: 1,
            name: 'Dior Sauvage Parfum',
            image: '/image/Men/Dior Sauvage Parfum.png',
            sex: 'Men',
            category: 'Unisex',
            style: 'Nam tính, Quyến rũ, Mạnh mẽ',
            fragrant: 'Aromantic Fougere (Hương Thơm Thảo Mộc)',
            origin: 'Ý',
            concentration: 'Eau De Toilette (EDT)',
            label: 'Men',
            price: 3790000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Dior',
            cart_quantity: 0,
            rating: 2.33,
            description: 'Dior Sauvage Eau De Toilette ra mắt từ năm 2015 đã làm “bấn loạn” giới yêu nước hoa bởi hương thơm vừa quyến rũ, vừa hoang dại. Và 2018 này hãng tung ra phiên bản Dior Sauvage Eau De Parfum tăng cường độ lưu hương để thỏa mãn các tín đồ nước hoa.'
        },
        {
            id: 2,
            name: 'Giorgio Armani Acqua Di Gio Pour Homme For Men',
            image: '/image/Men/Giorgio Armani Acqua Di Gio Pour Homme For Men.png',
            sex: 'Men',
            category: 'Unisex',
            style: 'Nam tính, Quyến rũ, Mạnh mẽ',
            fragrant: 'Aromantic Fougere (Hương Thơm Thảo Mộc)',
            origin: 'Ý',
            concentration: 'Eau De Toilette (EDT)',
            label: 'New',
            price: 3200000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Giorgio Armani',
            cart_quantity: 0,
            rating: 4.54,
            description: 'Giorgio Armani tạo ra hương nước hoa Giorgio Armani Acqua Di Gio được lấy cảm hứng từ những gì tinh túy nhất. Chai nước hoa được chính thức tung lên thị trường vào năm 1996 và vẫn được sử dụng rộng rãi tới bây giờ.'
        },
        {
            id: 3,
            name: 'Versace Eros For Men EDT',
            image: '/image/Men/Versace-Eros-For-Men_1.png',
            sex: 'Men',
            category: 'Unisex',
            style: 'Nam tính, Quyến rũ, Mạnh mẽ',
            fragrant: 'Aromantic Fougere (Hương Thơm Thảo Mộc)',
            origin: 'Ý',
            concentration: 'Eau De Toilette (EDT)',
            label: 'Hot',
            price: 3223000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Versace',
            cart_quantity: 0,
            rating: 4.71,
            description: 'Được giới thiệu lần đầu tại liên hoan phim Cannes 2012, Versace Eros lấy nguồn cảm hứng từ vị thần tình yêu trong thần thoại  thần thoại Hy Lạp(Eros là vị thần hy lạp của tình yêu). Versace Eros For Men là sự kết hợp và thể hiện của niềm đam mê vô tận và ham muốn mãnh liệt.'
        },
        {
            id: 4,
            name: 'Versace Pour Homme Cake',
            image: '/image/Men/Versace Pour Homme.png',
            sex: 'Men',
            category: 'Unisex',
            style: 'Nam tính, Quyến rũ, Mạnh mẽ',
            fragrant: 'Aromantic Fougere (Hương Thơm Thảo Mộc)',
            origin: 'Ý',
            concentration: 'Eau De Toilette (EDT)',
            label: 'Hot',
            price: 2068000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Versace',
            cart_quantity: 0,
            rating: '4.43',
            description: 'Mùi hương mới cho nam giới – Nước hoa Versace Pour Homme – là sự pha trộn các thành phần tinh chất có nguồn gốc Địa Trung Hải với hỗn hợp hương thơm hàng đầu rất phù hợp cho nam giới ngày nay: đó là những người đàn ông tri thức và tự tin, năng động, mạnh mẽ và đầy đam mê, sống hài hòa với thế giới tự nhiên.'
        },
        {
            id: 5,
            name: 'Dior Sauvage Elixir',
            image: '/image/Men/Dior Sauvage Elixir.png',
            sex: 'Men',
            category: 'Mini',
            style: 'Nam tính, Quyến rũ, Mạnh mẽ',
            fragrant: 'Aromantic Fougere (Hương Thơm Thảo Mộc)',
            origin: 'Ý',
            concentration: 'Eau De Toilette (EDT)',
            label: 'Hot',
            price: 3990000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Dior',
            cart_quantity: 0,
            rating: '4.83',
            description: 'Dior Sauvage Elixir là hương thơm mới trong bộ sưu tập Sauvage của Dior, được ra mắt vào mùa hè 2021 được tạo nên bởi nhà chế tạo nước hoa Francois Demachy. Dior Sauvage luôn lọt top nước hoa nam được yêu thích trong phân khúc designer.'
        },
        {
            id: 6,
            name: 'Bvlgari Aqva Pour Homme EDT',
            image: '/image/Men/Bvlgari-Aqva-Pour-Homme.png',
            sex: 'Men',
            category: 'Mini',
            style: 'Nam tính, Quyến rũ, Mạnh mẽ',
            fragrant: 'Aromantic Fougere (Hương Thơm Thảo Mộc)',
            origin: 'Ý',
            concentration: 'Eau De Toilette (EDT)',
            label: 'New',
            price: 2400000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Bvlgari',
            cart_quantity: 0,
            rating: '4.43',
            description: 'Dior Sauvage Elixir là hương thơm mới trong bộ sưu tập Sauvage của Dior, được ra mắt vào mùa hè 2021 được tạo nên bởi nhà chế tạo nước hoa Francois Demachy. Dior Sauvage luôn lọt top nước hoa nam được yêu thích trong phân khúc designer.'
        },
        {
            id: 7,
            name: 'Bvlgari Aqva Pour Homme EDT',
            image: '/image/Men/Giorgio-Armani-Code-Pour-Homme-EDT.png',
            sex: 'Men',
            category: 'Mini',
            style: 'Nam tính, Quyến rũ, Mạnh mẽ',
            fragrant: 'Aromantic Fougere (Hương Thơm Thảo Mộc)',
            origin: 'Ý',
            concentration: 'Eau De Toilette (EDT)',
            label: 'New',
            price: 2400000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Bvlgari',
            cart_quantity: 0,
            rating: '4.43',
            description: 'Dior Sauvage Elixir là hương thơm mới trong bộ sưu tập Sauvage của Dior, được ra mắt vào mùa hè 2021 được tạo nên bởi nhà chế tạo nước hoa Francois Demachy. Dior Sauvage luôn lọt top nước hoa nam được yêu thích trong phân khúc designer.'
        },
        {
            id: 8,
            name: 'Versace Dylan Blue Pour Homme',
            image: '/image/Men/Versace Dylan Blue Pour Homme.png',
            sex: 'Men',
            category: 'Mini',
            style: 'Nam tính, Quyến rũ, Mạnh mẽ',
            fragrant: 'Aromantic Fougere (Hương Thơm Thảo Mộc)',
            origin: 'Ý',
            concentration: 'Eau De Toilette (EDT)',
            label: 'New',
            price: 2990000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Versace',
            cart_quantity: 0,
            rating: '5.0',
            description: 'Dior Sauvage Elixir là hương thơm mới trong bộ sưu tập Sauvage của Dior, được ra mắt vào mùa hè 2021 được tạo nên bởi nhà chế tạo nước hoa Francois Demachy. Dior Sauvage luôn lọt top nước hoa nam được yêu thích trong phân khúc designer.'
        },
        {
            id: 9,
            name: 'Gucci Bloom For Women EDP',
            image: '/image/Women/Gucci Bloom For Women EDP.png',
            sex: 'Women',
            category: 'Mini',
            style: 'Quyến Rũ, Sang Trọng',
            fragrant: 'Floral ( Hương Hoa, Phấn Thơm )',
            origin: 'Pháp',
            concentration: 'Eau de Parfum (EDP)',
            label: 'New',
            price: 3490000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Gucci',
            cart_quantity: 0,
            rating: 4.14,
            description: 'Thương hiệu thời trang nổi tiếng Gucci vừa cho ra mắt sản phẩm nước hoa mới Gucci Bloom For Women EDP 100ml vào tháng 8/2017. Hương nước hoa đầu tiên dưới bàn tay của nhà sáng tạo Alesxandro Michele. Đây chính là hương nước hoa được yêu thích bậc nhất bởi sự quyến rũ mà nó mang lại.'
        },
        {
            id: 10,
            name: 'Versace Bright Crystal EDT',
            image: '/image/Women/Versace Bright Crystal EDT.png',
            sex: 'Women',
            category: 'Unisex',
            style: 'Quyến Rũ, Sang Trọng',
            fragrant: 'Floral ( Hương Hoa, Phấn Thơm )',
            origin: 'Pháp',
            concentration: 'Eau de Parfum (EDP)',
            label: 'Hot',
            price: 2442000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Versace',
            cart_quantity: 0,
            rating: 4.67,
            description: 'Năm 2006, Versace cho ra đời một loại nước hoa làm cả thế giới sửng sốt bởi mùi hương và thiết kế độc đáo, đó là Bright Crystal gợi tình, trong suốt và nổi bật. Lấy cảm hứng từ những sáng tạo độc đáo của người đi trước, Alberto Morillas đã vẻ nên một viên kim cương lấp lánh cho những buổi dạ tiệc lãng mạn để làm nên những câu chuyện tình đầy thăng hoa.'
        },
        {
            id: 11,
            name: 'Narciso Rodriguez For Her EDP',
            image: '/image/Women/Narciso Rodriguez For Her EDP.png',
            sex: 'Women',
            category: 'Unisex',
            style: 'Quyến Rũ, Sang Trọng',
            fragrant: 'Floral ( Hương Hoa, Phấn Thơm )',
            origin: 'Pháp',
            concentration: 'Eau de Parfum (EDP)',
            label: 'New',
            price: 2990000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Narciso Rodriguez',
            cart_quantity: 0,
            rating: 4.83,
            description: 'Narciso Rodriguez For Her là sản phẩm đầu tay của thương hiệu Narciso Rodriguez và cũng là chai nước hoa mà từ lúc ra mắt cho tới thời điểm hiện tại đều nằm trong Top hit hương nước hoa được nữ giới yêu thích nhất. Năm 2006 Narciso Rodriguez cho ra phiên bản EDP Narciso màu hồng pastel nhẹ nhàng cùng mùi hương ngọt ngào hiện đại và đầy cá tính được ví như vũ khí gây thương nhớ cao làm cho những cô nàng trở nên nổi bật và thu hút hơn bao giờ hết. '
        },
        {
            id: 12,
            name: 'Jean Paul Gaultier So Scandal EDP',
            image: '/image/Women/Jean Paul Gaultier So Scandal EDP.png',
            sex: 'Women',
            category: 'Unisex',
            style: 'Quyến Rũ, Sang Trọng',
            fragrant: 'Floral ( Hương Hoa, Phấn Thơm )',
            origin: 'Pháp',
            concentration: 'Eau de Parfum (EDP)',
            label: 'Hot',
            price: 3490000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Jean Paul Gaultier',
            cart_quantity: 0,
            rating: 5.00,
            description: 'Sau thành công của 1 loạt những phiên bản nước hoa Scandal trước đó, mới đây  năm 2020 hãng Jean Paul Gaultier đã cho ra đời một gương mặt mới đó là So Scandal EDP . Phiên bản lần đầy với tổng hợp những hương hoa trắng được đánh giá là đậm đà hơn, nông nàn và sâu lắng hơn, hưa hẹn mang đến những trải nghiệm thú vị cho người dùng.'
        },
        {
            id: 13,
            name: 'Armaf Club De Nuit Women EDP',
            image: '/image/Women/Armaf Club De Nuit Women EDP.png',
            sex: 'Women',
            category: 'Unisex',
            style: 'Quyến Rũ, Sang Trọng',
            fragrant: 'Floral ( Hương Hoa, Phấn Thơm )',
            origin: 'Pháp',
            concentration: 'Eau de Parfum (EDP)',
            label: 'Hot',
            price: 1420000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Armaf',
            cart_quantity: 0,
            rating: '4.43',
            description: 'Armaf Club De Nuit Women thể hiện một hương thơm tinh tế dành cho người phụ nữ với mùi hương đặc trưng của trái cây và bạc hà. Đó là một biểu hiện của sự sang trọng và quyến rũ khó cưỡng.'
        },
        {
            id: 14,
            name: 'Chanel N°1 De Chanel Leau Rouge',
            image: '/image/Women/Chanel N°1 De Chanel Leau Rouge.png',
            sex: 'Women',
            category: 'Unisex',
            style: 'Quyến Rũ, Sang Trọng',
            fragrant: 'Floral ( Hương Hoa, Phấn Thơm )',
            origin: 'Pháp',
            concentration: 'Eau de Parfum (EDP)',
            label: 'New',
            price: 3550000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Chanel',
            cart_quantity: 0,
            rating: '4.43',
            description: 'Armaf Club De Nuit Women thể hiện một hương thơm tinh tế dành cho người phụ nữ với mùi hương đặc trưng của trái cây và bạc hà. Đó là một biểu hiện của sự sang trọng và quyến rũ khó cưỡng.'
        },
        {
            id: 15,
            name: 'Bvlgari Omnia By Mary Katrantzou',
            image: '/image/Women/Bvlgari Omnia By Mary Katrantzou.png',
            sex: 'Women',
            category: 'Unisex',
            style: 'Quyến Rũ, Sang Trọng',
            fragrant: 'Floral ( Hương Hoa, Phấn Thơm )',
            origin: 'Pháp',
            concentration: 'Eau de Parfum (EDP)',
            label: 'New',
            price: 3550000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Bvlgari',
            cart_quantity: 0,
            rating: '4.43',
            description: 'Armaf Club De Nuit Women thể hiện một hương thơm tinh tế dành cho người phụ nữ với mùi hương đặc trưng của trái cây và bạc hà. Đó là một biểu hiện của sự sang trọng và quyến rũ khó cưỡng.'
        },
        {
            id: 16,
            name: 'Paco Rabanne Olympea Blossom',
            image: '/image/Women/Paco Rabanne Olympea Blossom.png',
            sex: 'Women',
            category: 'Mini',
            style: 'Quyến Rũ, Sang Trọng',
            fragrant: 'Floral ( Hương Hoa, Phấn Thơm )',
            origin: 'Pháp',
            concentration: 'Eau de Parfum (EDP)',
            label: 'New',
            price: 2990000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Paco Rabanne',
            cart_quantity: 0,
            rating: '4.93',
            description: 'Armaf Club De Nuit Women thể hiện một hương thơm tinh tế dành cho người phụ nữ với mùi hương đặc trưng của trái cây và bạc hà. Đó là một biểu hiện của sự sang trọng và quyến rũ khó cưỡng.'
        },
        {
            id: 17,
            name: 'Marc Jacobs Daisy Eau So Intense',
            image: '/image/Women/Marc Jacobs Daisy Eau So Intense.png',
            sex: 'Women',
            category: 'Mini',
            style: 'Quyến Rũ, Sang Trọng',
            fragrant: 'Floral ( Hương Hoa, Phấn Thơm )',
            origin: 'Pháp',
            concentration: 'Eau de Parfum (EDP)',
            label: 'New',
            price: 3050000,
            quantity: 100,
            year: 2018,
            inCart: false,
            brand: 'Marc Jacobs',
            cart_quantity: 0,
            rating: '4.93',
            description: 'Armaf Club De Nuit Women thể hiện một hương thơm tinh tế dành cho người phụ nữ với mùi hương đặc trưng của trái cây và bạc hà. Đó là một biểu hiện của sự sang trọng và quyến rũ khó cưỡng.'
        },
    ]